-- AlterTable
ALTER TABLE "links" ADD COLUMN     "clicks" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "conversions" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "desktopClicks" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mobileClicks" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "tabletClicks" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "topCountry" TEXT DEFAULT 'No data',
ADD COLUMN     "visitors" INTEGER NOT NULL DEFAULT 0;
